name: DC Security Scans

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - "*"

jobs:
  iac_security_scan:
    uses: doublecloud/security_workflows/.github/workflows/tf_security.yml@main
    with: 
      wiz_project_id: ${{ vars.WIZ_PROJECT_ID }}
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  dependency_vulnerability_scan:
    uses: doublecloud/security_workflows/.github/workflows/dependency_scan.yml@main
    with: 
      wiz_project_id: ${{ vars.WIZ_PROJECT_ID }}
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
